python true_listwise.py location_ST_1000
python true_listwise.py location_ST_1200
python true_listwise.py location_ST_1400
python true_listwise.py location_ST_1600
python true_listwise.py location_ST_1800
python true_listwise.py location_ST_2000

python true_listwise.py location_HV_1000
python true_listwise.py location_HV_1200
python true_listwise.py location_HV_1800
python true_listwise.py location_HV_2200
