python final_models.py final_loaded_data/location_HV_1000/weighed final_loaded_data/location_HV_1000/weighed final_trained_models/location_HV_1000/
python final_models.py final_loaded_data/location_HV_1200/weighed final_loaded_data/location_HV_1200/weighed final_trained_models/location_HV_1200/
python final_models.py final_loaded_data/location_HV_1650/weighed final_loaded_data/location_HV_1650/weighed final_trained_models/location_HV_1650/
python final_models.py final_loaded_data/location_HV_1800/weighed final_loaded_data/location_HV_1800/weighed final_trained_models/location_HV_1800/
python final_models.py final_loaded_data/location_HV_2200/weighed final_loaded_data/location_HV_2200/weighed final_trained_models/location_HV_2200/

python final_models.py final_loaded_data/location_ST_1000/weighed final_loaded_data/location_ST_1000/weighed final_trained_models/location_ST_1000/
python final_models.py final_loaded_data/location_ST_1200/weighed final_loaded_data/location_ST_1200/weighed final_trained_models/location_ST_1200/
python final_models.py final_loaded_data/location_ST_1400/weighed final_loaded_data/location_ST_1400/weighed final_trained_models/location_ST_1400/
python final_models.py final_loaded_data/location_ST_1600/weighed final_loaded_data/location_ST_1600/weighed final_trained_models/location_ST_1600/
python final_models.py final_loaded_data/location_ST_1650/weighed final_loaded_data/location_ST_1650/weighed final_trained_models/location_ST_1650/
python final_models.py final_loaded_data/location_ST_1800/weighed final_loaded_data/location_ST_1800/weighed final_trained_models/location_ST_1800/
python final_models.py final_loaded_data/location_ST_2000/weighed final_loaded_data/location_ST_2000/weighed final_trained_models/location_ST_2000/
